version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend && npm install

  build:
    commands:
      - cd frontend && npm run build

  post_build:
    commands:
      - aws s3 sync frontend/build/ s3://fdp-admin-portal --delete

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build