version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --prefix $CODEBUILD_SRC_DIR/frontend

  build:
    commands:
      - npm run build --prefix $CODEBUILD_SRC_DIR/frontend

  post_build:
    commands:
      - aws s3 sync $CODEBUILD_SRC_DIR/frontend/build/ s3://fdp-admin-portal --delete

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build